# Generated by Django 4.0.4 on 2022-04-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('publish_date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.BigIntegerField()),
                ('appropriate', models.CharField(choices=[('For kids', 'Under 8'), ('For Teens', '8 - 15'), ('For Adults', '+15')], default='For Teens', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
            ],
        ),
    ]
