# Generated by Django 4.0.4 on 2022-04-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(default=1, upload_to='static/book/images/'),
            preserve_default=False,
        ),
    ]
